### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by gossie** [JeTSkY1h/TodoAppExercise#2]
* Beim hinzufügen eines Tasks lädt das Board zu früh neu. Es kann vorkommen, dass das Board die Tasks neu holt, bevor das hinzufügen fertig ist. Das liegt daran, dass du nicht auf die Antwort vom POST wartest, bevor der GET Request gemacht wird.
```typescript
const handleClick = () => {
    postKanban({task: task, description: desc, status: TaskStatus.OPEN})
    props.fetchKanbans()
}
```
Das `fetchKanbans` darf erste gemacht werden, wenn das `Promise` von postKanban resolved.
```typescript
```typescript
const handleClick = () => {
    postKanban({task: task, description: desc, status: TaskStatus.OPEN})
        .then(props.fetchKanbans);
}
```
* Beim edit rufst du auch den POST Endpunkt auf. Der sollte eigentlich nur zum erzeugen neuer Tasks genutzt werden. Zum Editieren sollte ein PUT Request gemacht werden. Das mit dem POST funktioniert gerade, weil du im Payload den Task mit ID verschickst und die `HashMap` im Backend das alte Objekt überschreibt.

**Comment by JeTSkY1h** [comment]
implementiert.
